# Generated by Django 4.1.1 on 2022-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='Описание токена'
                    ),
                ),
                (
                    'asset_id',
                    models.CharField(max_length=255, verbose_name='Айди токена'),
                ),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
    ]
