version: '3.9'

services:

  postgres:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "
      python manage.py wait_for_database &&
      python manage.py migrate --no-input &&
      python manage.py collectstatic --no-input &&
      python manage.py create_default_superuser &&
      gunicorn HellaSwap.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./:/home/app/backend/
      - static_volume:/home/app/backend/static/
    env_file:
      - ./.env
      - ./.env.db
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8228:8228"
#      - "443:443"
    volumes:
      - static_volume:/home/app/backend/static/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
