# Generated by Django 4.1.1 on 2022-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gas_used',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Использованный газ'
            ),
        ),
    ]
