# Generated by Django 4.1.1 on 2022-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_gas_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(
                choices=[('done', 'выполнено'), ('pend', 'ожидается')],
                default='pend',
                max_length=4,
                verbose_name='Статус',
            ),
        ),
    ]
